name: Vorschlag
description: Einen Vorschlag machen
title: "Vorschlag: [Kurzer Titel]"
labels: ["vorschlag"]
body:
  - type: markdown
    attributes:
      value: |
        Wenn Du einen Vorschlag für das Projekt hast, dann kannst Du ihn hier eingeben.
        Vergiss bitte nicht, den Platzhalter-Text in dem Titel durch Deinen eigenen Titel zu ersetzen.
  - type: dropdown
    id: regarding
    attributes:
      label: Betroffener Projektteil
      description: |
        Welche Teile des Projektes betrifft der Vorschlag?
        Wenn Du nicht sicher bist, kannst Du dieses Feld frei lassen.
      multiple: true
      options:
        - Buch
        - Vorbereitungsblätter
        - Aufgabenblöcke
        - Videos
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Beschreib hier so kurz wie möglich Deinen Vorschlag.
        Wie sieht der Vorschlag aus? Welche Vorteile hat er für das Projekt?
  - type: markdown
    attributes:
      value: |
        Vielen Dank für Dein Interesse an dem Projekt.
        Wir wissen es sehr zu schätzen, dass Du Dir gedanken gemacht hast, wie man es weiter verbessern kann.